apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: az-keyvault-reader-sidecar-injector
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
