apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "az-keyvault-reader-sidecar-injector-prod"
  namespace: "kube-system"
  labels:
    k8s-app: "az-keyvault-reader-sidecar-injector"
    track: "prod"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        k8s-app: "az-keyvault-reader-sidecar-injector"
        track: "prod"
    spec:
      serviceAccountName: az-keyvault-reader-sidecar-injector
      volumes:
        - name: secrets
          secret:
            secretName: az-keyvault-reader-sidecar-injector
      containers:
        - name: "az-keyvault-reader-sidecar-injector"
          imagePullPolicy: Always
          image: cmendibl3/az-keyvault-reader-sidecar-injector:latest
          command: ["entrypoint.sh"]
          args: []
          ports:
            - name: https
              containerPort: 8443
          volumeMounts:
            - name: secrets
              mountPath: /var/lib/secrets
              livenessProbe:
                httpGet:
                  scheme: HTTPS
                  path: /health
                  port: https
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 3
          resources:
            requests:
              cpu: "0.5"
              memory: 1Gi
            limits:
              cpu: "0.5"
              memory: 2Gi
          env:
            - name: "TLS_CERT_FILE"
              value: "/var/lib/secrets/cert.crt"
            - name: "TLS_KEY_FILE"
              value: "/var/lib/secrets/cert.key"
            - name: "LOG_LEVEL"
              value: "2"
