apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: "cmendibl3-az-keyvault-reader-sidecar-injector-webhook"
  labels:
    app: az-keyvault-reader-sidecar-injector
    track: prod
webhooks:
  - name: "injector.mendible.com"
    failurePolicy: "Ignore" # we fail "open" if the webhook is down hard
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    clientConfig:
      service:
        name: "az-keyvault-reader-sidecar-injector-prod"
        namespace: "kube-system"
        path: "/mutate" # what /url/slug to send requests at
      # See README.md for how this was generated!
      caBundle: "__CA_BUNDLE_BASE64__"
