apiVersion: v1
kind: Service
metadata:
  name: az-keyvault-reader-injector-service
  namespace: kube-system
  labels:
    k8s-app: az-keyvault-reader-injector
    track: prod
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
  selector:
    k8s-app: az-keyvault-reader-injector
    track: prod
