apiVersion: v1
kind: ServiceAccount
metadata:
  name: az-keyvault-reader-sidecar-injector
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
