---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: az-keyvault-reader
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: az-keyvault-reader
        aadpodidbinding: requires-vault
      annotations:
        az.keyvault.reader/keyvault: aksegresstest
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            - sleep
            - "3600"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "4Mi"
              cpu: "100m"
            limits:
              memory: "8Mi"
              cpu: "200m"
      restartPolicy: Always
